
-- Create the database
CREATE DATABASE IF NOT EXISTS exercises;
USE exercises;

-- Create the exercises table
CREATE TABLE IF NOT EXISTS exercise (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exercise_name VARCHAR(255) NOT NULL,
    push VARCHAR(255),
    pull VARCHAR(255),
    legs VARCHAR(255),
    cardio VARCHAR(255),
    crossfit VARCHAR(255),
    sets INT,
    reps INT
);

-- Insert sample data into the exercises table
INSERT INTO exercise (exercise_name, push, pull, legs, cardio, crossfit, sets, reps) VALUES
('Bench Press', 'Bench Press', NULL, NULL, NULL, NULL, 4, 10),
('Overhead Press', 'Overhead Press', NULL, NULL, NULL, NULL, 3, 12),
('Push-ups', 'Push-ups', NULL, NULL, NULL, NULL, 4, 15),
('Pull-ups', NULL, 'Pull-ups', NULL, NULL, NULL, 3, 8),
('Bent Over Rows', NULL, 'Bent Over Rows', NULL, NULL, NULL, 3, 10),
('Deadlifts', NULL, 'Deadlifts', NULL, NULL, NULL, 4, 8),
('Squats', NULL, NULL, 'Squats', NULL, NULL, 4, 12),
('Leg Press', NULL, NULL, 'Leg Press', NULL, NULL, 3, 15),
('Lunges', NULL, NULL, 'Lunges', NULL, NULL, 3, 12),
('Running', NULL, NULL, NULL, 'Running', NULL, NULL, NULL),
('Cycling', NULL, NULL, NULL, 'Cycling', NULL, NULL, NULL),
('Jump Rope', NULL, NULL, NULL, 'Jump Rope', NULL, NULL, NULL),
('Burpees', NULL, NULL, NULL, NULL, 'Burpees', 3, 10),
('Kettlebell Swings', NULL, NULL, NULL, NULL, 'Kettlebell Swings', 3, 15),
('Box Jumps', NULL, NULL, NULL, NULL, 'Box Jumps', 3, 12),
('Dips', 'Dips', NULL, NULL, NULL, NULL, 4, 10),
('Lat Pulldowns', NULL, 'Lat Pulldowns', NULL, NULL, NULL, 3, 12),
('Leg Curls', NULL, NULL, 'Leg Curls', NULL, NULL, 3, 15),
('Rowing', NULL, NULL, NULL, 'Rowing', NULL, NULL, NULL),
('Thrusters', NULL, NULL, NULL, NULL, 'Thrusters', 3, 10),
('Hammer Curl', NULL, 'Hammer Curl', NULL, NULL, NULL, 3, 12),
('Tricep Extension', 'Tricep Extension', NULL, NULL, NULL, NULL, 3, 12),
('Calf Raises', NULL, NULL, 'Calf Raises', NULL, NULL, 4, 15),
('Step-ups', NULL, NULL, 'Step-ups', NULL, NULL, 3, 12),
('Mountain Climbers', NULL, NULL, NULL, 'Mountain Climbers', NULL, 4, 20),
('Battle Ropes', NULL, NULL, NULL, 'Battle Ropes', NULL, 3, 15),
('Snatch', NULL, NULL, NULL, NULL, 'Snatch', 3, 10),
('Clean and Jerk', NULL, NULL, NULL, NULL, 'Clean and Jerk', 3, 8),
('Pistol Squats', NULL, NULL, 'Pistol Squats', NULL, NULL, 3, 6),
('Glute Bridge', NULL, NULL, 'Glute Bridge', NULL, NULL, 3, 15),
('Side Plank', NULL, NULL, NULL, NULL, 'Side Plank', 3, 30),
('Russian Twist', NULL, NULL, NULL, NULL, 'Russian Twist', 3, 20),
('Sledgehammer Swings', NULL, NULL, NULL, NULL, 'Sledgehammer Swings', 3, 12),
('Windshield Wipers', NULL, NULL, NULL, NULL, 'Windshield Wipers', 3, 15),
('Bulgarian Split Squat', NULL, NULL, 'Bulgarian Split Squat', NULL, NULL, 3, 12),
('Tire Flips', NULL, NULL, NULL, NULL, 'Tire Flips', 3, 10),
('Goblet Squat', NULL, NULL, 'Goblet Squat', NULL, NULL, 3, 15),
('Farmer’s Walk', NULL, NULL, NULL, NULL, 'Farmer’s Walk', 4, 60),
('Pull Through', NULL, 'Pull Through', NULL, NULL, NULL, 3, 15);

INSERT INTO exercise (exercise_name, push, pull, legs, cardio, crossfit, sets, reps) VALUES
('Cable Flyes', 'Cable Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Incline Bench Press', 'Incline Bench Press', NULL, NULL, NULL, NULL, 4, 10),
('Decline Bench Press', 'Decline Bench Press', NULL, NULL, NULL, NULL, 4, 10),
('Arnold Press', 'Arnold Press', NULL, NULL, NULL, NULL, 3, 12),
('Chest Dips', 'Chest Dips', NULL, NULL, NULL, NULL, 4, 10),
('Rear Delt Fly', NULL, 'Rear Delt Fly', NULL, NULL, NULL, 3, 12),
('Seated Row', NULL, 'Seated Row', NULL, NULL, NULL, 3, 10),
('T-Bar Row', NULL, 'T-Bar Row', NULL, NULL, NULL, 3, 10),
('Good Mornings', NULL, 'Good Mornings', NULL, NULL, NULL, 3, 12),
('Single Leg Deadlift', NULL, 'Single Leg Deadlift', NULL, NULL, NULL, 3, 10),
('Hip Thrust', NULL, NULL, 'Hip Thrust', NULL, NULL, 4, 12),
('Front Squat', NULL, NULL, 'Front Squat', NULL, NULL, 4, 10),
('Sumo Deadlift', NULL, 'Sumo Deadlift', NULL, NULL, NULL, 4, 8),
('Leg Extension', NULL, NULL, 'Leg Extension', NULL, NULL, 4, 15),
('Side Lunges', NULL, NULL, 'Side Lunges', NULL, NULL, 3, 12),
('Elliptical Trainer', NULL, NULL, NULL, 'Elliptical Trainer', NULL, NULL, NULL),
('Swimming', NULL, NULL, NULL, 'Swimming', NULL, NULL, NULL),
('Sprinting', NULL, NULL, NULL, 'Sprinting', NULL, NULL, NULL),
('High Knees', NULL, NULL, NULL, 'High Knees', NULL, 4, 20),
('Butt Kicks', NULL, NULL, NULL, 'Butt Kicks', NULL, 4, 20),
('Med Ball Slams', NULL, NULL, NULL, NULL, 'Med Ball Slams', 3, 15),
('Battle Rope Slams', NULL, NULL, NULL, NULL, 'Battle Rope Slams', 3, 15),
('Wall Balls', NULL, NULL, NULL, NULL, 'Wall Balls', 3, 20),
('Handstand Push-ups', 'Handstand Push-ups', NULL, NULL, NULL, NULL, 3, 8),
('Bodyweight Rows', NULL, 'Bodyweight Rows', NULL, NULL, NULL, 3, 12),
('Cable Crunch', NULL, NULL, NULL, NULL, 'Cable Crunch', 4, 15),
('Hanging Leg Raise', NULL, NULL, NULL, NULL, 'Hanging Leg Raise', 3, 12),
('Face Pulls', NULL, 'Face Pulls', NULL, NULL, NULL, 3, 15),
('Chest Press Machine', 'Chest Press Machine', NULL, NULL, NULL, NULL, 4, 10),
('Reverse Fly Machine', NULL, 'Reverse Fly Machine', NULL, NULL, NULL, 3, 12),
('Hack Squat', NULL, NULL, 'Hack Squat', NULL, NULL, 4, 10);

INSERT INTO exercise (exercise_name, push, pull, legs, cardio, crossfit, sets, reps) VALUES
('Chest Flyes', 'Chest Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Dumbbell Bench Press', 'Dumbbell Bench Press', NULL, NULL, NULL, NULL, 4, 10),
('Incline Dumbbell Press', 'Incline Dumbbell Press', NULL, NULL, NULL, NULL, 3, 12),
('Decline Dumbbell Press', 'Decline Dumbbell Press', NULL, NULL, NULL, NULL, 3, 10),
('Military Press', 'Military Press', NULL, NULL, NULL, NULL, 4, 8),
('Lateral Raises', 'Lateral Raises', NULL, NULL, NULL, NULL, 3, 15),
('Rear Delt Rows', NULL, 'Rear Delt Rows', NULL, NULL, NULL, 3, 12),
('Lat Pullover', NULL, 'Lat Pullover', NULL, NULL, NULL, 3, 10),
('Cable Rows', NULL, 'Cable Rows', NULL, NULL, NULL, 3, 12),
('Straight Arm Pulldown', NULL, 'Straight Arm Pulldown', NULL, NULL, NULL, 3, 15),
('Bulgarian Split Squats', NULL, NULL, 'Bulgarian Split Squats', NULL, NULL, 4, 12),
('Hack Squats', NULL, NULL, 'Hack Squats', NULL, NULL, 4, 10),
('Romanian Deadlifts', NULL, 'Romanian Deadlifts', NULL, NULL, NULL, 4, 12),
('Box Squats', NULL, NULL, 'Box Squats', NULL, NULL, 4, 10),
('Hip Abductor Machine', NULL, NULL, 'Hip Abductor Machine', NULL, NULL, 3, 15),
('Hip Adductor Machine', NULL, NULL, 'Hip Adductor Machine', NULL, NULL, 3, 15),
('Calf Press on Leg Press', NULL, NULL, 'Calf Press on Leg Press', NULL, NULL, 4, 20),
('Standing Calf Raises', NULL, NULL, 'Standing Calf Raises', NULL, NULL, 4, 15),
('Incline Dumbbell Flyes', 'Incline Dumbbell Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Cable Lateral Raises', 'Cable Lateral Raises', NULL, NULL, NULL, NULL, 3, 15),
('Single Arm Dumbbell Row', NULL, 'Single Arm Dumbbell Row', NULL, NULL, NULL, 3, 10),
('Chest Supported Row', NULL, 'Chest Supported Row', NULL, NULL, NULL, 3, 12),
('Seated Calf Raises', NULL, NULL, 'Seated Calf Raises', NULL, NULL, 4, 20),
('Ab Rollout', NULL, NULL, NULL, NULL, 'Ab Rollout', 3, 10),
('Dragon Flags', NULL, NULL, NULL, NULL, 'Dragon Flags', 3, 6),
('Hanging Knee Raise', NULL, NULL, NULL, NULL, 'Hanging Knee Raise', 3, 12),
('Incline Leg Press', NULL, NULL, 'Incline Leg Press', NULL, NULL, 4, 12),
('Sled Push', NULL, NULL, NULL, NULL, 'Sled Push', 3, 30),
('Kettlebell Goblet Squat', NULL, NULL, 'Kettlebell Goblet Squat', NULL, NULL, 3, 15),
('Plyometric Lunges', NULL, NULL, 'Plyometric Lunges', NULL, NULL, 3, 12),
('Medicine Ball Throws', NULL, NULL, NULL, NULL, 'Medicine Ball Throws', 3, 10),
('Sledgehammer Hits', NULL, NULL, NULL, NULL, 'Sledgehammer Hits', 3, 15),
('Skater Jumps', NULL, NULL, NULL, 'Skater Jumps', NULL, 3, 20);

INSERT INTO exercise (exercise_name, push, pull, legs, cardio, crossfit, sets, reps) VALUES
('Chest Flyes', 'Chest Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Dumbbell Bench Press', 'Dumbbell Bench Press', NULL, NULL, NULL, NULL, 4, 10),
('Incline Dumbbell Press', 'Incline Dumbbell Press', NULL, NULL, NULL, NULL, 3, 12),
('Decline Dumbbell Press', 'Decline Dumbbell Press', NULL, NULL, NULL, NULL, 3, 10),
('Military Press', 'Military Press', NULL, NULL, NULL, NULL, 4, 8),
('Lateral Raises', 'Lateral Raises', NULL, NULL, NULL, NULL, 3, 15),
('Rear Delt Rows', NULL, 'Rear Delt Rows', NULL, NULL, NULL, 3, 12),
('Lat Pullover', NULL, 'Lat Pullover', NULL, NULL, NULL, 3, 10),
('Cable Rows', NULL, 'Cable Rows', NULL, NULL, NULL, 3, 12),
('Straight Arm Pulldown', NULL, 'Straight Arm Pulldown', NULL, NULL, NULL, 3, 15),
('Bulgarian Split Squats', NULL, NULL, 'Bulgarian Split Squats', NULL, NULL, 4, 12),
('Hack Squats', NULL, NULL, 'Hack Squats', NULL, NULL, 4, 10),
('Romanian Deadlifts', NULL, 'Romanian Deadlifts', NULL, NULL, NULL, 4, 12),
('Box Squats', NULL, NULL, 'Box Squats', NULL, NULL, 4, 10),
('Hip Abductor Machine', NULL, NULL, 'Hip Abductor Machine', NULL, NULL, 3, 15),
('Hip Adductor Machine', NULL, NULL, 'Hip Adductor Machine', NULL, NULL, 3, 15),
('Calf Press on Leg Press', NULL, NULL, 'Calf Press on Leg Press', NULL, NULL, 4, 20),
('Standing Calf Raises', NULL, NULL, 'Standing Calf Raises', NULL, NULL, 4, 15),
('Incline Dumbbell Flyes', 'Incline Dumbbell Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Cable Lateral Raises', 'Cable Lateral Raises', NULL, NULL, NULL, NULL, 3, 15),
('Single Arm Dumbbell Row', NULL, 'Single Arm Dumbbell Row', NULL, NULL, NULL, 3, 10),
('Chest Supported Row', NULL, 'Chest Supported Row', NULL, NULL, NULL, 3, 12),
('Seated Calf Raises', NULL, NULL, 'Seated Calf Raises', NULL, NULL, 4, 20),
('Ab Rollout', NULL, NULL, NULL, NULL, 'Ab Rollout', 3, 10),
('Dragon Flags', NULL, NULL, NULL, NULL, 'Dragon Flags', 3, 6),
('Hanging Knee Raise', NULL, NULL, NULL, NULL, 'Hanging Knee Raise', 3, 12),
('Incline Leg Press', NULL, NULL, 'Incline Leg Press', NULL, NULL, 4, 12),
('Sled Push', NULL, NULL, NULL, NULL, 'Sled Push', 3, 30),
('Kettlebell Goblet Squat', NULL, NULL, 'Kettlebell Goblet Squat', NULL, NULL, 3, 15),
('Plyometric Lunges', NULL, NULL, 'Plyometric Lunges', NULL, NULL, 3, 12),
('Medicine Ball Throws', NULL, NULL, NULL, NULL, 'Medicine Ball Throws', 3, 10),
('Sledgehammer Hits', NULL, NULL, NULL, NULL, 'Sledgehammer Hits', 3, 15),
('Skater Jumps', NULL, NULL, NULL, 'Skater Jumps', NULL, 3, 20);

INSERT INTO exercise (exercise_name, push, pull, legs, cardio, crossfit, sets, reps) VALUES
('Dumbbell Flyes', 'Dumbbell Flyes', NULL, NULL, NULL, NULL, 3, 12),
('Cable Chest Press', 'Cable Chest Press', NULL, NULL, NULL, NULL, 3, 12),
('Push Press', 'Push Press', NULL, NULL, NULL, NULL, 4, 8),
('Reverse Pec Deck', NULL, 'Reverse Pec Deck', NULL, NULL, NULL, 3, 15),
('Chest Press', 'Chest Press', NULL, NULL, NULL, NULL, 4, 10),
('Cable Bicep Curls', NULL, 'Cable Bicep Curls', NULL, NULL, NULL, 3, 12),
('Preacher Curls', NULL, 'Preacher Curls', NULL, NULL, NULL, 3, 10),
('Hammer Strength Rows', NULL, 'Hammer Strength Rows', NULL, NULL, NULL, 3, 12),
('Dumbbell Shrugs', NULL, 'Dumbbell Shrugs', NULL, NULL, NULL, 3, 15),
('Rear Delt Flyes', NULL, 'Rear Delt Flyes', NULL, NULL, NULL, 3, 15),
('Hack Squat Machine', NULL, NULL, 'Hack Squat Machine', NULL, NULL, 4, 10),
('Reverse Lunges', NULL, NULL, 'Reverse Lunges', NULL, NULL, 3, 12),
('Single Leg Press', NULL, NULL, 'Single Leg Press', NULL, NULL, 3, 15),
('Cable Kickbacks', NULL, NULL, 'Cable Kickbacks', NULL, NULL, 3, 12),
('Box Step-ups', NULL, NULL, 'Box Step-ups', NULL, NULL, 3, 12);